stages:
  - test
  - build

test_1:
  stage: test
  image: golang:1.17
  script:
   - go test .
  tags:
     - yandex

build_2:
  stage: build
  image: docker:latest
  script:
   - docker build .
  tags:
     - cloud
